# Generated by Django 6.0.2 on 2026-02-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='like',
            new_name='likes',
        ),
    ]
